In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import sklearn.datasets
import sklearn.linear_model
import pandas as pd

In [2]:
data = pd.read_csv("ML_Task.csv")

In [3]:
data.head()

X1  X2  X3  Output
0   1   1   1       1
1   0   1   1       0
2   1   0   1       0
3   0   0   1       1
4   1   1   0       0

In [4]:
print(data.columns)

Index(['X1', 'X2', 'X3', 'Output'], dtype='object')


In [5]:
X = data[['X1','X2','X3']].to_numpy()

In [6]:

print(X.shape)
X = X.T

(8, 3)


In [7]:
Y = data['Output'].to_numpy()

In [8]:
Y = np.resize(Y,(1,8))

In [9]:
Y.shape

(1, 8)

In [10]:
n_x = 3
n_h = 3
n_y = 1
m = X.shape[1]

**Now the weights of NN params**

In [11]:
W1 = np.random.randn(n_h,n_x)
b1 = np.random.randn(n_h,1)
W2 = np.random.randn(n_y,n_h)
b2 = np.random.randn(n_y,1)
print(W1)

[[ 1.01788973  0.98038376  0.38513521]
 [-2.08435209  2.04551426 -0.21043895]
 [ 1.45057656  0.76253031 -0.17870498]]


In [12]:
learning_rate = 0.8

**Training**

In [13]:
for _ in range(2000):
    ## Fwd prop
    Z1 = np.dot(W1,X) + b1
    A1 = 1/(1+np.exp(-Z1))
    Z2 = np.dot(W2,A1) + b2
    A2 = 1/(1+np.exp(-Z2))
    
    ##Cost
    #cost = -(Y*np.log(A2) + (1-Y)*np.log(1-A2))
    
    ## Backward Prop
    dZ2 = A2 - Y
    dW2 = np.dot(dZ2,A1.T)/m
    db2 = np.sum(dZ2,axis=1,keepdims=True)/m
    dZ1 = np.dot(W2.T,dZ2)*(1 - np.power(A1, 2))
    dW1 = np.dot(dZ1,X.T)/m
    db1 = np.sum(dZ1,axis=1,keepdims=True)/m
    
    ## Update Params
    W1 = W1 - dW1 * learning_rate
    W2 = W2 - dW2 * learning_rate
    b1 = b1 - db1 * learning_rate
    b2 = b2 - db2 * learning_rate
    


In [14]:
W1

array([[ 33.47363675,  33.76807807,  -2.05807761],
       [-68.31133166,  71.58405559, -69.5541024 ],
       [119.64203642, -91.41767481, -48.10658831]])

**Prediction**


In [15]:
def predict(X):
    Z1 = np.dot(W1,X) + b1
    A1 = 1/(1+np.exp(-Z1))
    Z2 = np.dot(W2,A1) + b2
    A2 = 1/(1+np.exp(-Z2))
    return A2#np.round(A2)

In [16]:
Test_X = X
print(predict(Test_X))
print(Y)

[[0.99999998 0.05131626 0.01585977 0.94067385 0.10628918 0.84827812
  0.94666753 0.08315425]]
[[1 0 0 1 0 1 1 0]]


In [17]:
W1

array([[ 33.47363675,  33.76807807,  -2.05807761],
       [-68.31133166,  71.58405559, -69.5541024 ],
       [119.64203642, -91.41767481, -48.10658831]])

In [18]:
b1

array([[-32.33613341],
       [ -0.41855109],
       [-27.52807944]])

In [19]:
W2

array([[ 14.82785966, -13.01149648, -11.11510979]])

In [20]:
b2

array([[2.76354627]])